matrix:
  include:
  - os: linux
    language: android
    dist: trusty
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28
      - sys-img-armeabi-v7a-google_apis-28
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-google-android-support
    jdk: oraclejdk8
    sudo: true
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    before_script:
    - ls
    - cd ./teste/android
    - ls
    - cd ..
    - cd ..
    - yes | sdkmanager --update 
    - ls -la
    - chmod +x .
    script:
    - ls
    - flutter create myapp
    - cd myapp
    - flutter build appbundle
    - ls
install:
- git clone -b 'v1.12.13+hotfix.8' --depth 1 https://github.com/flutter/flutter.git
- export PATH="$PATH:`pwd`/flutter/bin"
cache:
  directories:
  - "$HOME/.pub-cache"
before_install:
- openssl aes-256-cbc -K $encrypted_27d4849cc909_key -iv $encrypted_27d4849cc909_iv
  -in api-play-store-key.json.enc -out ./teste/android/fastlane/api-play-store-key.json
  -d
- openssl aes-256-cbc -K $encrypted_eeb603d14591_key -iv $encrypted_eeb603d14591_iv
  -in key.properties.enc -out ./teste/android/key.properties -d
- openssl aes-256-cbc -K $encrypted_a1878d22f282_key -iv $encrypted_a1878d22f282_iv
  -in key.jks.enc -out ./teste/android/key.jks -d
- openssl aes-256-cbc -K $encrypted_049c52812871_key -iv $encrypted_049c52812871_iv
  -in nao.txt.enc -out nao.txt -d
- openssl aes-256-cbc -K $encrypted_ab3d90f89345_key -iv $encrypted_ab3d90f89345_iv
  -in oi.txt.enc -out oi.txt -d
